//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babel.EnglishEmitter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Babel.EnglishEmitter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Adjective List
        ///// and http://www.abcteach.com/abclists/adjectives.htm
        ///// from http://www.paulnoll.com/China/Teach/English-adjectives-2.html
        ///abundant
        ///adorable
        ///afraid
        ///agreeable
        ///alert
        ///alive
        ///amused
        ///ancient
        ///angry
        ///annoyed
        ///anxious
        ///arrogant
        ///ashamed
        ///average
        ///awful
        ///bad
        ///beautiful
        ///better
        ///bewildered
        ///big
        ///bitter
        ///black
        ///blonde
        ///bloody
        ///blue
        ///blushing
        ///boiling
        ///bored
        ///brainy
        ///brave
        ///breakable
        ///breezy
        ///brief
        ///bright
        ///broad
        ///broken
        ///bumpy
        ///busy
        ///calm
        ///careful
        ///cautious
        ///charming
        ///cheerful
        ///chilly
        ///ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adjectives {
            get {
                return ResourceManager.GetString("Adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &quot;Base Form&quot; &quot;Plural&quot;
        ///// http://www2.gsu.edu/~wwwesl/egw/crump.htm
        ///
        ///// ending in f cases
        ///calf calves 
        ///elf elves 
        ///half halves 
        ///hoof hooves 
        ///knife knives 
        ///leaf leaves 
        ///life lives 
        ///loaf loaves 
        ///scarf scarfs/scarves 
        ///self selves 
        ///sheaf sheaves 
        ///shelf shelves 
        ///thief thieves 
        ///wife wives 
        ///wolf wolves 
        ///
        ///// desended
        ///fireman firemen 
        ///foot feet 
        ///goose geese 
        ///louse lice 
        ///man men 
        ///mouse mice 
        ///tooth teeth 
        ///woman women 
        ///child children 
        ///ox oxen 
        ///die dice
        ///person people
        ///
        ///// ending in o
        ///au [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Irregular_Nouns {
            get {
                return ResourceManager.GetString("Irregular_Nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &quot;Base Form&quot; &quot;Simple Past Tense&quot; &quot;Past Participle&quot;
        ///// http://www2.gsu.edu/~wwwesl/egw/verbs.htm
        ///awake awoke awoken 
        ///be was/were been 
        ///bear bore born 
        ///beat beat beat 
        ///become became become 
        ///begin began begun 
        ///bend bent bent 
        ///beset beset beset 
        ///bet bet bet 
        ///bid bid bid
        ///bind bound bound 
        ///bite bit  bitten 
        ///bleed bled bled 
        ///blow blew blown 
        ///break broke broken 
        ///breed bred bred 
        ///bring brought brought 
        ///broadcast broadcast broadcast 
        ///build built built 
        ///burn burnt burnt 
        ///burst burst burst 
        ///buy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Irregular_Verbs {
            get {
                return ResourceManager.GetString("Irregular_Verbs", resourceCulture);
            }
        }
    }
}
