using System;
using System.Collections.Generic;
using System.Text;

using Babel;

namespace ChatterBot
{
    public enum Source
    {
		/// <summary>
		/// Used for things that the computer said or did.
		/// </summary>
		Self,

		/// <summary>
		/// Used for things that the human client said or did.
		/// </summary>
		Client,

		/// <summary>
		/// Events that were generated by the environment.
		/// </summary>
		Environment,

		/// <summary>
		/// Thoughts that were created by the computer for internal use.
		/// </summary>
		Assumption
    }
}